export type SignalOriginType = "real" | "competitor" | "inferred" | "fallback" | "unknown";

/**
 * SignalComposition represents the LINEAGE SIGNAL COUNTS, not raw data counts.
 *
 * WHAT SIGNAL COUNTS REPRESENT:
 * Each count (real, competitor, inferred, etc.) is the number of SignalLineageEntry
 * items tagged with that originType. A single raw data point (e.g., one scraped
 * Instagram post) can produce MULTIPLE lineage signals if it is decomposed into
 * audience signals, positioning signals, etc. Conversely, one inferred signal
 * may be synthesized from zero raw data (AI-generated).
 *
 * HOW AGGREGATION WORKS:
 * 1. Each engine tags its outputs with an originType at creation (real, competitor,
 *    inferred, fallback, unknown).
 * 2. When a downstream engine derives new signals from upstream signals, it inherits
 *    the originType of the parent signal (propagation rule: tag at source, inherit
 *    on derive, never mutate).
 * 3. computeSignalComposition() counts ALL lineage entries (including inherited/derived
 *    ones) and computes ratios. This means the total count reflects the number of
 *    signal ENTRIES flowing through the pipeline, not the number of unique raw data
 *    sources.
 * 4. trustedRatio = (real + competitor) / total — signals grounded in actual data.
 * 5. dominantType = whichever originType has the highest count.
 *
 * IMPORTANT DISTINCTION:
 * - "real: 5" means 5 lineage entries originated from user-provided data, NOT that
 *   there are 5 raw data records.
 * - "inferred: 20" means 20 lineage entries were AI-generated or derived without
 *   direct data backing.
 * - A strategy with real=2, inferred=50 has a low trustedRatio (~3.8%), meaning
 *   the strategy is heavily dependent on AI inference rather than ground truth.
 */
export interface SignalComposition {
  /** Number of lineage entries from user-provided/first-party data */
  real: number;
  /** Number of lineage entries from scraped competitor data */
  competitor: number;
  /** Number of lineage entries generated by AI without direct data backing */
  inferred: number;
  /** Number of lineage entries from fallback/default values */
  fallback: number;
  /** Number of lineage entries with unclassified origin */
  unknown: number;
  /** Total lineage entry count across all origin types */
  total: number;
  /** The originType with the highest count */
  dominantType: SignalOriginType;
  competitorRatio: number;
  realRatio: number;
  inferredRatio: number;
  fallbackRatio: number;
  unknownRatio: number;
  /** (real + competitor) / total — proportion grounded in actual data */
  trustedRatio: number;
}

export function computeSignalComposition(entries: SignalLineageEntry[]): SignalComposition {
  const counts: Record<SignalOriginType, number> = { real: 0, competitor: 0, inferred: 0, fallback: 0, unknown: 0 };
  for (const e of entries) {
    const t = e.originType || "unknown";
    counts[t] = (counts[t] || 0) + 1;
  }
  const total = entries.length || 1;
  let dominantType: SignalOriginType = "unknown";
  let maxCount = 0;
  for (const [type, count] of Object.entries(counts)) {
    if (count > maxCount) {
      maxCount = count;
      dominantType = type as SignalOriginType;
    }
  }
  const trustedCount = counts.real + counts.competitor;
  return {
    ...counts,
    total: entries.length,
    dominantType,
    competitorRatio: counts.competitor / total,
    realRatio: counts.real / total,
    inferredRatio: counts.inferred / total,
    fallbackRatio: counts.fallback / total,
    unknownRatio: counts.unknown / total,
    trustedRatio: trustedCount / total,
  };
}

export function formatCompositionLog(comp: SignalComposition): string {
  return `real=${comp.real} competitor=${comp.competitor} inferred=${comp.inferred} fallback=${comp.fallback} unknown=${comp.unknown} | dominant=${comp.dominantType} | realRatio=${(comp.realRatio * 100).toFixed(0)}% competitorRatio=${(comp.competitorRatio * 100).toFixed(0)}%`;
}

export interface SignalLineageEntry {
  signalId: string;
  originEngine: string;
  signalCategory: string;
  signalText: string;
  parentSignalId: string | null;
  hopDepth: number;
  signalPath: string[];
  createdAt: string;
  originType: SignalOriginType;
}

export function generateLineageId(engine: string, category: string, index: number): string {
  const prefix = engine.toUpperCase().replace(/[^A-Z0-9]/g, "_");
  const cat = category.toUpperCase().replace(/[^A-Z0-9]/g, "_");
  return `${prefix}_${cat}_${String(index + 1).padStart(3, "0")}`;
}

export function createSourceLineageEntry(
  engine: string,
  category: string,
  signalText: string,
  index: number,
  originType: SignalOriginType = "unknown",
): SignalLineageEntry {
  const signalId = generateLineageId(engine, category, index);
  return {
    signalId,
    originEngine: engine,
    signalCategory: category,
    signalText: signalText.slice(0, 200),
    parentSignalId: null,
    hopDepth: 0,
    signalPath: [engine],
    createdAt: new Date().toISOString(),
    originType,
  };
}

export function createDerivedLineageEntry(
  engine: string,
  category: string,
  signalText: string,
  parentEntry: SignalLineageEntry,
  index: number,
): SignalLineageEntry {
  const signalId = generateLineageId(engine, category, index);
  return {
    signalId,
    originEngine: parentEntry.originEngine,
    signalCategory: category,
    signalText: signalText.slice(0, 200),
    parentSignalId: parentEntry.signalId,
    hopDepth: parentEntry.hopDepth + 1,
    signalPath: [...parentEntry.signalPath, engine],
    createdAt: new Date().toISOString(),
    originType: parentEntry.originType || "unknown",
  };
}

export function findBestParentSignal(
  claimText: string,
  upstreamLineage: SignalLineageEntry[],
): SignalLineageEntry | null {
  const lower = claimText.toLowerCase();
  const claimWords = lower.split(/\s+/).filter(w => w.length > 3);
  if (claimWords.length === 0) return null;

  let bestMatch: SignalLineageEntry | null = null;
  let bestScore = 0;

  for (const entry of upstreamLineage) {
    const signalWords = new Set(entry.signalText.toLowerCase().split(/\s+/).filter(w => w.length > 3));
    let matches = 0;
    for (const w of claimWords) {
      if (signalWords.has(w)) matches++;
    }
    if (matches >= 1 && matches > bestScore) {
      bestScore = matches;
      bestMatch = entry;
    }
  }

  return bestMatch;
}

export function mergeLineageArrays(...arrays: SignalLineageEntry[][]): SignalLineageEntry[] {
  const seen = new Set<string>();
  const result: SignalLineageEntry[] = [];
  for (const arr of arrays) {
    for (const entry of arr) {
      if (!seen.has(entry.signalId)) {
        seen.add(entry.signalId);
        result.push(entry);
      }
    }
  }
  return result;
}

function normalizeLineageEntry(raw: any): SignalLineageEntry {
  return {
    signalId: raw.signalId || "",
    originEngine: raw.originEngine || "",
    signalCategory: raw.signalCategory || "",
    signalText: raw.signalText || "",
    parentSignalId: raw.parentSignalId || null,
    hopDepth: raw.hopDepth || 0,
    signalPath: raw.signalPath || [],
    createdAt: raw.createdAt || "",
    originType: raw.originType || "unknown",
  };
}

export function parseLineageFromSnapshot(raw: string | null): SignalLineageEntry[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed.map(normalizeLineageEntry);
  } catch {
    return [];
  }
}

export interface QualifyingSignal {
  signalId: string;
  originEngine: string;
  category: string;
  text: string;
  hopDepth: number;
  originType: SignalOriginType;
}

export function extractQualifyingSignals(lineage: SignalLineageEntry[]): QualifyingSignal[] {
  return lineage
    .filter(e => e.hopDepth === 0)
    .map(e => ({
      signalId: e.signalId,
      originEngine: e.originEngine,
      category: e.signalCategory,
      text: e.signalText,
      hopDepth: e.hopDepth,
      originType: e.originType,
    }));
}

export interface PerformanceMetrics {
  impressions?: number;
  clicks?: number;
  conversions?: number;
  spend?: number;
  revenue?: number;
  cpa?: number;
  roas?: number;
  ctr?: number;
}

export function bridgePerformanceToLineage(metrics: PerformanceMetrics, campaignId: string): SignalLineageEntry[] {
  const entries: SignalLineageEntry[] = [];
  let idx = 0;

  if (metrics.conversions && metrics.conversions > 0) {
    entries.push(createSourceLineageEntry("performance", "conversion_signal", `${metrics.conversions} conversions recorded`, idx++, "real"));
  }
  if (metrics.spend && metrics.spend > 0) {
    const cpa = metrics.cpa || (metrics.conversions && metrics.conversions > 0 ? metrics.spend / metrics.conversions : null);
    if (cpa !== null) {
      entries.push(createSourceLineageEntry("performance", "cpa_signal", `CPA: $${cpa.toFixed(2)}`, idx++, "real"));
    }
  }
  if (metrics.revenue && metrics.revenue > 0 && metrics.spend && metrics.spend > 0) {
    const roas = metrics.roas || metrics.revenue / metrics.spend;
    entries.push(createSourceLineageEntry("performance", "roas_signal", `ROAS: ${roas.toFixed(2)}x`, idx++, "real"));
  }
  if (metrics.clicks && metrics.clicks > 0 && metrics.impressions && metrics.impressions > 0) {
    const ctr = metrics.ctr || metrics.clicks / metrics.impressions;
    entries.push(createSourceLineageEntry("performance", "ctr_signal", `CTR: ${(ctr * 100).toFixed(2)}%`, idx++, "real"));
  }
  if (metrics.impressions && metrics.impressions > 0) {
    entries.push(createSourceLineageEntry("performance", "reach_signal", `${metrics.impressions} impressions`, idx++, "real"));
  }

  if (entries.length > 0) {
    console.log(`[SignalLineage] PERFORMANCE_BRIDGE | campaign=${campaignId} | realSignals=${entries.length} | metrics=${Object.entries(metrics).filter(([,v]) => v && v > 0).map(([k]) => k).join(",")}`);
  }
  return entries;
}

export const MIN_QUALIFYING_SIGNALS = 3;

export interface SignalGroundingResult {
  totalClaims: number;
  groundedClaims: number;
  ungroundedClaims: number;
  groundingRatio: number;
  signalSufficient: boolean;
  groundedEntries: SignalLineageEntry[];
  strippedClaims: string[];
  composition: SignalComposition;
}

export function validateClaimGrounding(
  claims: string[],
  upstreamLineage: SignalLineageEntry[],
  engine: string,
  category: string,
): SignalGroundingResult {
  const groundedEntries: SignalLineageEntry[] = [];
  const strippedClaims: string[] = [];
  let idx = 0;

  for (const claim of claims) {
    const parent = findBestParentSignal(claim, upstreamLineage);
    if (parent) {
      groundedEntries.push(createDerivedLineageEntry(engine, category, claim, parent, idx));
      idx++;
    } else {
      strippedClaims.push(claim);
    }
  }

  const totalClaims = claims.length;
  const groundedClaims = groundedEntries.length;
  return {
    totalClaims,
    groundedClaims,
    ungroundedClaims: strippedClaims.length,
    groundingRatio: totalClaims > 0 ? groundedClaims / totalClaims : 0,
    signalSufficient: upstreamLineage.filter(e => e.hopDepth === 0).length >= MIN_QUALIFYING_SIGNALS,
    groundedEntries,
    strippedClaims,
    composition: computeSignalComposition(groundedEntries),
  };
}
