export const ENGINE_VERSION = 4;
export const STATUS = {
    COMPLETE: "COMPLETE",
    MISSING_DEPENDENCY: "MISSING_DEPENDENCY",
    GUARD_BLOCKED: "GUARD_BLOCKED",
    FALLBACK: "FALLBACK",
    DECISION_GATE_DOWNGRADE: "DECISION_GATE_DOWNGRADE",
    FUNNEL_RECONSTRUCTED: "FUNNEL_RECONSTRUCTED",
    AWARENESS_BLOCKED: "AWARENESS_BLOCKED",
};
export const FUNNEL_ROLE_THRESHOLDS = {
    awareness: 0.55,
    nurture: 0.50,
    conversion: 0.50,
};
export const CHANNEL_FUNNEL_CAPABILITIES = {
    instagram_organic: { awareness: 0.90, nurture: 0.45, conversion: 0.20, persuasionDepth: "shallow" },
    instagram_paid: { awareness: 0.75, nurture: 0.50, conversion: 0.70, persuasionDepth: "moderate" },
    facebook_organic: { awareness: 0.55, nurture: 0.55, conversion: 0.20, persuasionDepth: "moderate" },
    facebook_paid: { awareness: 0.65, nurture: 0.50, conversion: 0.80, persuasionDepth: "moderate" },
    google_search: { awareness: 0.15, nurture: 0.10, conversion: 0.95, persuasionDepth: "shallow" },
    google_organic: { awareness: 0.60, nurture: 0.55, conversion: 0.65, persuasionDepth: "deep" },
    youtube_organic: { awareness: 0.80, nurture: 0.80, conversion: 0.35, persuasionDepth: "deep" },
    youtube_paid: { awareness: 0.75, nurture: 0.50, conversion: 0.55, persuasionDepth: "moderate" },
    email_marketing: { awareness: 0.10, nurture: 0.90, conversion: 0.85, persuasionDepth: "deep" },
    tiktok_organic: { awareness: 0.95, nurture: 0.30, conversion: 0.15, persuasionDepth: "shallow" },
    tiktok_paid: { awareness: 0.85, nurture: 0.30, conversion: 0.50, persuasionDepth: "shallow" },
    linkedin_organic: { awareness: 0.50, nurture: 0.75, conversion: 0.40, persuasionDepth: "deep" },
    linkedin_paid: { awareness: 0.45, nurture: 0.55, conversion: 0.70, persuasionDepth: "moderate" },
    referral_program: { awareness: 0.25, nurture: 0.40, conversion: 0.90, persuasionDepth: "moderate" },
    community_building: { awareness: 0.40, nurture: 0.85, conversion: 0.30, persuasionDepth: "deep" },
    partnerships: { awareness: 0.55, nurture: 0.50, conversion: 0.55, persuasionDepth: "moderate" },
};
export const CHANNEL_TYPES = [
    "social_organic",
    "social_paid",
    "search_paid",
    "search_organic",
    "email",
    "referral",
    "direct",
    "community",
    "partnerships",
    "content_platform",
];
export const PERSUASION_COMPATIBILITY_THRESHOLD = 0.50;
export const CHANNEL_DEFINITIONS = {
    instagram_organic: { label: "Instagram Organic", type: "social_organic", baseEfficiency: 0.65, minBudget: 0 },
    instagram_paid: { label: "Instagram Paid", type: "social_paid", baseEfficiency: 0.70, minBudget: 500 },
    facebook_organic: { label: "Facebook Organic", type: "social_organic", baseEfficiency: 0.50, minBudget: 0 },
    facebook_paid: { label: "Facebook Paid", type: "social_paid", baseEfficiency: 0.72, minBudget: 500 },
    google_search: { label: "Google Search Ads", type: "search_paid", baseEfficiency: 0.75, minBudget: 1000 },
    google_organic: { label: "Google SEO", type: "search_organic", baseEfficiency: 0.60, minBudget: 0 },
    youtube_organic: { label: "YouTube Organic", type: "content_platform", baseEfficiency: 0.55, minBudget: 0 },
    youtube_paid: { label: "YouTube Ads", type: "social_paid", baseEfficiency: 0.68, minBudget: 1000 },
    email_marketing: { label: "Email Marketing", type: "email", baseEfficiency: 0.80, minBudget: 0 },
    tiktok_organic: { label: "TikTok Organic", type: "social_organic", baseEfficiency: 0.58, minBudget: 0 },
    tiktok_paid: { label: "TikTok Ads", type: "social_paid", baseEfficiency: 0.62, minBudget: 500 },
    linkedin_organic: { label: "LinkedIn Organic", type: "social_organic", baseEfficiency: 0.45, minBudget: 0 },
    linkedin_paid: { label: "LinkedIn Ads", type: "social_paid", baseEfficiency: 0.55, minBudget: 1000 },
    referral_program: { label: "Referral Program", type: "referral", baseEfficiency: 0.85, minBudget: 0 },
    community_building: { label: "Community Building", type: "community", baseEfficiency: 0.50, minBudget: 0 },
    partnerships: { label: "Strategic Partnerships", type: "partnerships", baseEfficiency: 0.60, minBudget: 0 },
};
export const CHANNEL_DIFFERENTIATION_PROFILES = {
    instagram_organic: {
        audienceDiscoveryDynamics: "Algorithm-driven discovery via Explore, Reels, and hashtag feeds; visual-first audience matching",
        contentVelocityRequirement: "High — 5-7 posts/week including Stories, Reels, and carousel content for sustained visibility",
        algorithmAmplification: "Strong Reels amplification; engagement-weighted distribution; saves and shares prioritized",
        conversionLikelihood: "Moderate — discovery-heavy but limited direct conversion paths; relies on link-in-bio and DM funnels",
    },
    tiktok_organic: {
        audienceDiscoveryDynamics: "For-You-Page (FYP) interest-graph discovery; content-first, not follower-first; viral potential high",
        contentVelocityRequirement: "Very high — 1-3 videos/day recommended; algorithm favors consistent daily posting",
        algorithmAmplification: "Strongest viral potential among social platforms; content quality over follower count; completion rate key metric",
        conversionLikelihood: "Lower direct conversion — audience skews younger; best for awareness and consideration stages",
    },
    facebook_organic: {
        audienceDiscoveryDynamics: "Group-based and share-driven discovery; declining organic reach for brand pages; community-centric",
        contentVelocityRequirement: "Moderate — 3-5 posts/week; Groups require daily engagement and moderation",
        algorithmAmplification: "Limited for pages; Groups and Reels have better reach; meaningful interaction signals weighted",
        conversionLikelihood: "Moderate — mature platform with established conversion paths but declining organic engagement",
    },
    linkedin_organic: {
        audienceDiscoveryDynamics: "Professional network graph; content surfaces via connections' engagement; B2B-focused discovery",
        contentVelocityRequirement: "Low-moderate — 2-4 posts/week; thought leadership and document posts perform best",
        algorithmAmplification: "Comments and dwell time heavily weighted; personal profiles outperform company pages",
        conversionLikelihood: "High for B2B; professional intent audience; longer sales cycles but qualified leads",
    },
    instagram_paid: {
        audienceDiscoveryDynamics: "Meta Ads Manager targeting; lookalike audiences, interest-based, and retargeting segments",
        contentVelocityRequirement: "Moderate — 3-5 ad creatives per campaign with regular refresh cycles (2-4 weeks)",
        algorithmAmplification: "Auction-based; creative quality score and relevance diagnostics influence delivery and cost",
        conversionLikelihood: "High — strong conversion infrastructure with pixel tracking, shopping integration, and lead forms",
    },
    facebook_paid: {
        audienceDiscoveryDynamics: "Meta Ads Manager with broadest targeting options; custom audiences, lookalikes, detailed targeting",
        contentVelocityRequirement: "Moderate — 3-5 creatives; advantage+ campaigns reduce manual creative rotation needs",
        algorithmAmplification: "Mature auction system; advantage+ optimization; broad targeting increasingly outperforming narrow",
        conversionLikelihood: "High — most mature conversion tracking ecosystem; CAPI integration, offline conversions support",
    },
    google_search: {
        audienceDiscoveryDynamics: "Intent-based; captures active search demand; keyword-driven targeting",
        contentVelocityRequirement: "Low — ad copy rotation with 3-5 headlines/descriptions; landing page optimization ongoing",
        algorithmAmplification: "Quality Score driven; relevance, landing page experience, and expected CTR determine ad rank",
        conversionLikelihood: "Highest — captures bottom-of-funnel intent; direct conversion path from search to landing page",
    },
    google_organic: {
        audienceDiscoveryDynamics: "Search intent matching via SEO; topical authority and backlink profile driven",
        contentVelocityRequirement: "Low but consistent — 2-4 high-quality articles/month; existing content optimization ongoing",
        algorithmAmplification: "E-E-A-T signals; topical clusters; freshness signals for time-sensitive queries",
        conversionLikelihood: "High for bottom-of-funnel content; informational content builds pipeline; long payback period",
    },
    youtube_organic: {
        audienceDiscoveryDynamics: "Recommendation algorithm and search; Shorts discovery separate from long-form; watch history driven",
        contentVelocityRequirement: "Moderate — 1-2 long-form videos/week or 3-5 Shorts/week for channel growth",
        algorithmAmplification: "Watch time and click-through rate primary signals; Shorts have independent discovery feed",
        conversionLikelihood: "Moderate — strong trust-building but conversion requires clear CTAs and description links",
    },
    youtube_paid: {
        audienceDiscoveryDynamics: "Google Ads targeting; in-stream, discovery, and Shorts ad placements; audience and contextual targeting",
        contentVelocityRequirement: "Low — 2-3 video ad variants; skippable vs non-skippable formats require different creatives",
        algorithmAmplification: "Auction-based; view rate and engagement signals optimize delivery; connected TV expanding reach",
        conversionLikelihood: "Moderate — awareness and consideration strong; conversion requires multi-touch attribution",
    },
    tiktok_paid: {
        audienceDiscoveryDynamics: "TikTok Ads Manager; interest and behavior targeting; Spark Ads amplify organic content",
        contentVelocityRequirement: "High — creative fatigue fast; 5-10 ad creatives recommended with 1-2 week refresh",
        algorithmAmplification: "Creative-quality driven auction; native-feeling content outperforms polished ads significantly",
        conversionLikelihood: "Growing — TikTok Shop integration improving; pixel maturity catching up to Meta",
    },
    linkedin_paid: {
        audienceDiscoveryDynamics: "Professional firmographic targeting; job title, company size, industry, seniority-based",
        contentVelocityRequirement: "Low — 2-3 ad variants; document ads and thought leader ads perform well",
        algorithmAmplification: "Auction-based; higher CPMs but precise B2B targeting; engagement rate signals matter",
        conversionLikelihood: "High for B2B — qualified professional audience; lead gen forms with pre-filled fields",
    },
    email_marketing: {
        audienceDiscoveryDynamics: "Owned audience; list-based; segmentation by behavior, purchase history, and engagement",
        contentVelocityRequirement: "Moderate — 2-4 emails/week; automation sequences reduce manual effort",
        algorithmAmplification: "Inbox placement algorithm; sender reputation, engagement, and authentication drive deliverability",
        conversionLikelihood: "Highest among owned channels — direct communication, personalization, and clear CTAs",
    },
    referral_program: {
        audienceDiscoveryDynamics: "Existing customer network; word-of-mouth amplification; incentive-driven acquisition",
        contentVelocityRequirement: "Low — program setup and periodic incentive updates; automated referral tracking",
        algorithmAmplification: "Trust-based; social proof inherent; quality depends on customer satisfaction and incentive structure",
        conversionLikelihood: "Very high — warm introductions; pre-qualified leads through trusted recommendations",
    },
    community_building: {
        audienceDiscoveryDynamics: "Organic community growth; member-to-member discovery; value-driven attraction",
        contentVelocityRequirement: "Moderate-high — daily engagement, weekly events/content, community moderation ongoing",
        algorithmAmplification: "Network effects; member engagement drives organic growth; platform-dependent (Discord/Slack/Forum)",
        conversionLikelihood: "Moderate — long nurture cycle but high LTV; converts through trust and belonging",
    },
    partnerships: {
        audienceDiscoveryDynamics: "Partner audience access; co-marketing reach; complementary audience overlap",
        contentVelocityRequirement: "Low — joint content pieces, co-branded campaigns, event participation",
        algorithmAmplification: "Cross-promotion amplification; combined audience reach; credibility transfer between brands",
        conversionLikelihood: "Moderate-high — credibility boost from partner endorsement; depends on partner audience alignment",
    },
};
export const OBJECTIVE_FIT_MATRIX = {
    instagram_organic: { awarenessFit: 0.85, nurtureFit: 0.60, conversionFit: 0.30 },
    instagram_paid: { awarenessFit: 0.70, nurtureFit: 0.55, conversionFit: 0.75 },
    facebook_organic: { awarenessFit: 0.55, nurtureFit: 0.65, conversionFit: 0.25 },
    facebook_paid: { awarenessFit: 0.65, nurtureFit: 0.50, conversionFit: 0.80 },
    google_search: { awarenessFit: 0.20, nurtureFit: 0.15, conversionFit: 0.90 },
    google_organic: { awarenessFit: 0.60, nurtureFit: 0.50, conversionFit: 0.65 },
    youtube_organic: { awarenessFit: 0.80, nurtureFit: 0.70, conversionFit: 0.30 },
    youtube_paid: { awarenessFit: 0.75, nurtureFit: 0.45, conversionFit: 0.55 },
    email_marketing: { awarenessFit: 0.15, nurtureFit: 0.90, conversionFit: 0.80 },
    tiktok_organic: { awarenessFit: 0.90, nurtureFit: 0.40, conversionFit: 0.20 },
    tiktok_paid: { awarenessFit: 0.80, nurtureFit: 0.35, conversionFit: 0.55 },
    linkedin_organic: { awarenessFit: 0.55, nurtureFit: 0.75, conversionFit: 0.40 },
    linkedin_paid: { awarenessFit: 0.50, nurtureFit: 0.55, conversionFit: 0.70 },
    referral_program: { awarenessFit: 0.30, nurtureFit: 0.40, conversionFit: 0.85 },
    community_building: { awarenessFit: 0.45, nurtureFit: 0.85, conversionFit: 0.35 },
    partnerships: { awarenessFit: 0.60, nurtureFit: 0.50, conversionFit: 0.55 },
};
export const AWARENESS_CHANNEL_MAP = {
    unaware: ["social_organic", "content_platform", "community"],
    problem_aware: ["social_organic", "social_paid", "search_organic", "content_platform"],
    solution_aware: ["search_paid", "social_paid", "email", "content_platform"],
    product_aware: ["search_paid", "email", "referral", "direct"],
    most_aware: ["email", "referral", "direct", "partnerships"],
};
export const PERSUASION_CHANNEL_COMPATIBILITY = {
    education_first: ["content_platform", "social_organic", "email", "community"],
    proof_driven: ["social_paid", "search_paid", "email", "referral"],
    authority_led: ["social_organic", "content_platform", "partnerships", "community"],
    scarcity_urgency: ["social_paid", "email", "direct"],
    trust_building: ["email", "community", "referral", "content_platform"],
};
export const LAYER_NAMES = [
    "audience_density_assessment",
    "awareness_channel_mapping",
    "persuasion_mode_compatibility",
    "budget_constraint_check",
    "cost_efficiency_scoring",
    "risk_assessment",
    "channel_fit_scoring",
    "guard_layer",
    "decision_gate",
];
export const LAYER_WEIGHTS = {
    audience_density_assessment: 0.16,
    awareness_channel_mapping: 0.20,
    persuasion_mode_compatibility: 0.14,
    budget_constraint_check: 0.10,
    cost_efficiency_scoring: 0.12,
    risk_assessment: 0.10,
    channel_fit_scoring: 0.08,
    guard_layer: 0.05,
    decision_gate: 0.05,
};
export const ORGANIC_CHANNELS = new Set([
    "instagram_organic",
    "facebook_organic",
    "google_organic",
    "youtube_organic",
    "tiktok_organic",
    "linkedin_organic",
    "email_marketing",
    "referral_program",
    "community_building",
    "partnerships",
]);
export const PAID_CHANNELS = new Set([
    "instagram_paid",
    "facebook_paid",
    "google_search",
    "youtube_paid",
    "tiktok_paid",
    "linkedin_paid",
]);
export const CONVERSION_INJECTION_PRIORITY = [
    "google_search",
    "email_marketing",
    "facebook_paid",
    "referral_program",
    "instagram_paid",
    "linkedin_paid",
];
export const PERSUASION_CORRECTION_FLOOR = 0.35;
export const CHANNEL_SCALABILITY = {
    instagram_organic: 0.60,
    instagram_paid: 0.85,
    facebook_organic: 0.40,
    facebook_paid: 0.90,
    google_search: 0.95,
    google_organic: 0.70,
    youtube_organic: 0.75,
    youtube_paid: 0.80,
    email_marketing: 0.65,
    tiktok_organic: 0.80,
    tiktok_paid: 0.75,
    linkedin_organic: 0.45,
    linkedin_paid: 0.70,
    referral_program: 0.50,
    community_building: 0.35,
    partnerships: 0.55,
};
export const BOUNDARY_HARD_PATTERNS = {
    "marketing copy": /\b(marketing copy|ad copy|sales copy|copywriting)\b/i,
    "ad creatives": /\b(ad creative|creative asset|banner design|creative brief)\b/i,
    "content calendar": /\b(content calendar|editorial calendar|posting schedule)\b/i,
    "funnel redesign": /\b(funnel redesign|new funnel|redesign funnel)\b/i,
    "offer redesign": /\b(offer redesign|new offer|redesign offer)\b/i,
    "persuasion frameworks": /\b(persuasion framework|persuasion technique|influence model)\b/i,
    "scripts": /\b(sales script|cold call script|outreach script)\b/i,
};
export const BOUNDARY_SOFT_PATTERNS = [
    { pattern: /\b(hook|hooks|opening hook)\b/gi, domain: "hook", replacement: "entry trigger" },
    { pattern: /\b(headline|headlines)\b/gi, domain: "headline", replacement: "attention signal" },
    { pattern: /\b(scroll.?stop)\b/gi, domain: "scroll stop", replacement: "attention capture" },
];
export const CHANNEL_ROLE_REGISTRY = {
    instagram_organic: {
        channelKey: "instagram_organic",
        role: "discovery",
        allowedAwarenessStages: ["unaware", "problem_aware", "solution_aware"],
        blockedAwarenessStages: [],
        restrictionRules: ["Interrupt/discovery channel — best for top-of-funnel audience building"],
    },
    instagram_paid: {
        channelKey: "instagram_paid",
        role: "discovery",
        allowedAwarenessStages: ["problem_aware", "solution_aware", "product_aware"],
        blockedAwarenessStages: ["unaware"],
        restrictionRules: ["Paid discovery requires minimum problem awareness for ad targeting effectiveness"],
    },
    facebook_organic: {
        channelKey: "facebook_organic",
        role: "discovery",
        allowedAwarenessStages: ["unaware", "problem_aware", "solution_aware"],
        blockedAwarenessStages: [],
        restrictionRules: ["Community-driven discovery — groups and shares for awareness building"],
    },
    facebook_paid: {
        channelKey: "facebook_paid",
        role: "discovery",
        allowedAwarenessStages: ["problem_aware", "solution_aware", "product_aware"],
        blockedAwarenessStages: ["unaware"],
        restrictionRules: ["Paid discovery requires problem awareness minimum for effective targeting"],
    },
    google_search: {
        channelKey: "google_search",
        role: "conversion",
        allowedAwarenessStages: ["solution_aware", "product_aware", "most_aware"],
        blockedAwarenessStages: ["unaware", "problem_aware"],
        restrictionRules: ["Intent-capture channel — audience MUST have existing search intent", "HARD BLOCK for unaware/problem_aware — they don't search for solutions they don't know exist"],
    },
    google_organic: {
        channelKey: "google_organic",
        role: "nurture",
        allowedAwarenessStages: ["problem_aware", "solution_aware", "product_aware", "most_aware"],
        blockedAwarenessStages: ["unaware"],
        restrictionRules: ["SEO content serves problem-aware+ audiences searching for information"],
    },
    youtube_organic: {
        channelKey: "youtube_organic",
        role: "discovery",
        allowedAwarenessStages: ["unaware", "problem_aware", "solution_aware"],
        blockedAwarenessStages: [],
        restrictionRules: ["Broad discovery via algorithm recommendations — deep content builds trust"],
    },
    youtube_paid: {
        channelKey: "youtube_paid",
        role: "discovery",
        allowedAwarenessStages: ["problem_aware", "solution_aware", "product_aware"],
        blockedAwarenessStages: ["unaware"],
        restrictionRules: ["Paid video discovery — requires problem awareness for ad relevance"],
    },
    email_marketing: {
        channelKey: "email_marketing",
        role: "nurture",
        allowedAwarenessStages: ["problem_aware", "solution_aware", "product_aware", "most_aware"],
        blockedAwarenessStages: ["unaware"],
        restrictionRules: ["Owned audience nurture — requires existing relationship/opt-in"],
    },
    tiktok_organic: {
        channelKey: "tiktok_organic",
        role: "discovery",
        allowedAwarenessStages: ["unaware", "problem_aware", "solution_aware"],
        blockedAwarenessStages: [],
        restrictionRules: ["Strongest discovery channel — FYP algorithm surfaces content to cold audiences"],
    },
    tiktok_paid: {
        channelKey: "tiktok_paid",
        role: "discovery",
        allowedAwarenessStages: ["problem_aware", "solution_aware"],
        blockedAwarenessStages: ["unaware"],
        restrictionRules: ["Paid channel — unaware audiences must be reached via organic/community channels only"],
    },
    linkedin_organic: {
        channelKey: "linkedin_organic",
        role: "nurture",
        allowedAwarenessStages: ["problem_aware", "solution_aware", "product_aware"],
        blockedAwarenessStages: ["unaware"],
        restrictionRules: ["Professional network nurture — B2B trust and authority building"],
    },
    linkedin_paid: {
        channelKey: "linkedin_paid",
        role: "conversion",
        allowedAwarenessStages: ["solution_aware", "product_aware", "most_aware"],
        blockedAwarenessStages: ["unaware", "problem_aware"],
        restrictionRules: ["High-CPM conversion channel — only viable for audiences with solution/product awareness"],
    },
    referral_program: {
        channelKey: "referral_program",
        role: "conversion",
        allowedAwarenessStages: ["product_aware", "most_aware"],
        blockedAwarenessStages: ["unaware", "problem_aware", "solution_aware"],
        restrictionRules: ["Requires existing customers to refer — audience must already know the product"],
    },
    community_building: {
        channelKey: "community_building",
        role: "nurture",
        allowedAwarenessStages: ["unaware", "problem_aware", "solution_aware", "product_aware"],
        blockedAwarenessStages: [],
        restrictionRules: ["Long-term nurture through belonging and trust — works across awareness stages"],
    },
    partnerships: {
        channelKey: "partnerships",
        role: "nurture",
        allowedAwarenessStages: ["problem_aware", "solution_aware", "product_aware", "most_aware"],
        blockedAwarenessStages: ["unaware"],
        restrictionRules: ["Cross-audience trust transfer — partner audience must have minimum awareness"],
    },
};
export const AWARENESS_STAGE_ALLOWED_ROLES = {
    unaware: ["discovery"],
    problem_aware: ["discovery", "nurture"],
    solution_aware: ["discovery", "nurture", "conversion"],
    product_aware: ["nurture", "conversion"],
    most_aware: ["conversion", "nurture"],
};
export const AWARENESS_BLOCKED_CHANNEL_TYPES = {
    unaware: ["social_paid", "search_paid", "search_organic", "email", "referral", "direct", "partnerships"],
    problem_aware: ["search_paid", "referral", "direct"],
};
export const AWARENESS_INJECTION_PRIORITY = {
    unaware: ["tiktok_organic", "instagram_organic", "youtube_organic", "facebook_organic", "community_building"],
    problem_aware: ["instagram_organic", "youtube_organic", "tiktok_organic", "facebook_organic", "google_organic"],
    solution_aware: CONVERSION_INJECTION_PRIORITY,
    product_aware: CONVERSION_INJECTION_PRIORITY,
    most_aware: ["email_marketing", "referral_program", "google_search"],
};
