import { aiChat } from "../ai-client";
import { callCommercialReasoner } from "../commercial-reasoning/llm-call";
import { type EvidenceRegistryEntry } from "./strategic-brief-context";

export interface LLMClaim {
  claimId: string;
  claimText: string;
  claimType: string;
  evidenceRefs: string[];
  criticality: "critical" | "secondary";
  factuality: "observed" | "calculated" | "inferred";
}

export interface LLMBriefResponse {
  eventId: string;
  executiveSummary: string;
  strategicInterpretation: string;
  likelyStrategicObjective: string;
  directionOfMovement: string;
  affectedStrategyAreas: string[];
  impactOnOurStrategy: string;
  marketSignificance: string;
  strategicImportance: "low" | "medium" | "high";
  recommendation: "ignore" | "monitor" | "review";
  modelProposedConfidence: number;
  evidenceRefs: string[];
  missingEvidence: string[];
  assumptions: string[];
  claims: LLMClaim[];
}

export interface ClaimJudgeResult {
  claimId: string;
  verdict: "supported" | "partially_supported" | "unsupported";
  violations: string[];
  judgeReason: string;
}

export interface JudgeResult {
  verdict: "PASS" | "REJECT";
  claims: ClaimJudgeResult[];
}

const GENERATOR_SYSTEM_PROMPT = `You are a strategic reasoning engine. You interpret a confirmed Watchtower market event using a registry of verified context evidence.

You must respond ONLY with a JSON object matching this schema:
{
  "eventId": "string",
  "executiveSummary": "string (1-2 sentences summarizing the change; or 'INSUFFICIENT_EVIDENCE' if evidence is too thin to draw strategic value)",
  "strategicInterpretation": "string (detailed explanation of the strategic meaning of this event)",
  "likelyStrategicObjective": "string (the competitor's likely goal: e.g. increase conversion, counter churn, pivot narrative)",
  "directionOfMovement": "string (description of the vector of change, e.g. premium pricing, high-cadence posting)",
  "affectedStrategyAreas": ["string (e.g. pricing, offer, positioning, funnel)"],
  "impactOnOurStrategy": "string (potential implications for OUR campaign/strategy, phrased as potential impacts, not guaranteed outcomes)",
  "marketSignificance": "string (how significant this is in the competitive landscape)",
  "strategicImportance": "low" | "medium" | "high",
  "recommendation": "ignore" | "monitor" | "review",
  "modelProposedConfidence": 0-100,
  "evidenceRefs": ["string"],
  "missingEvidence": ["string (what metrics or signals are missing that would strengthen this analysis)"],
  "assumptions": ["string (any assumptions made during interpretation)"],
  "claims": [
    {
      "claimId": "string (unique identifier, e.g. CL-1)",
      "claimText": "string (verbatim assertion representing one granular observation or inference)",
      "claimType": "string (competitor_strategy | market_trend)",
      "evidenceRefs": ["string (matching refs from the registry)"],
      "criticality": "critical" | "secondary",
      "factuality": "observed" | "calculated" | "inferred"
    }
  ]
}

STRICT DOCTRINE RULES:
1. Grounding: Every claim and statement must be strictly grounded in the evidence registry. Do not invent any numbers, names, or unobserved events.
2. Avoid Speculative Motives/Intent: Do NOT assert unobserved competitor intent or causality (e.g. "attempt to revitalize engagement", "seeking to counter churn", "intent to increase perceived value") as factual statements unless explicitly stated in the evidence details. Observations must stick strictly to observable facts (e.g. "Competitor introduced new Q&A content format"). Inferences must be clearly qualified (e.g. "appears aligned with a content refresh").
3. Evidence References: Every claim must cite the exact evidence refs (e.g. EV-1, BIZ-PLAN, BIZ-ROOT) it draws from.
4. No stack traces, credentials, or API keys in output.
5. Effects must be phrased as potential strategic implications, not guaranteed outcomes. Causation must not be claimed unless explicitly supported.
6. If the evidence registry is too thin to analyze the event, set executiveSummary to "INSUFFICIENT_EVIDENCE" and output empty lists for claims.`;

const JUDGE_SYSTEM_PROMPT = `You are a strict grounding judge. You receive (a) a verified EVIDENCE REGISTRY with context facts and (b) a list of claims generated by an AI strategic reasoning engine.

Evaluate each claim:
- "supported" if all assertions are grounded in the cited evidence registry refs.
- "partially_supported" if the core facts are grounded and any inferences are qualified and logical, with clear limitations noted.
- "unsupported" if it asserts facts, numbers, or unobserved competitor motives not present in the cited evidence registry items, or overstates causality.

Overall verdict rules:
- Set "verdict": "PASS" if all critical claims are "supported" or "partially_supported" (no unsupported critical claims and no fabricated numbers).
- Set "verdict": "REJECT" only if a critical claim is "unsupported" or if claims contain fabricated facts/numbers.

You must respond ONLY with a JSON object matching this schema:
{
  "verdict": "PASS" | "REJECT",
  "claims": [
    {
      "claimId": "string",
      "verdict": "supported" | "partially_supported" | "unsupported",
      "violations": ["string describing specific grounding violation"],
      "judgeReason": "string explaining the verdict"
    }
  ]
}`;

// Deterministic guards implementation
export function validateBriefDeterministic(
  brief: LLMBriefResponse,
  registry: EvidenceRegistryEntry[]
): string[] {
  const violations: string[] = [];
  const validRefs = new Set(registry.map((r) => r.ref));

  // 1. Check recommendation value
  const allowedRecs = ["ignore", "monitor", "review"];
  if (!allowedRecs.includes(brief.recommendation)) {
    violations.push(`Invalid recommendation value: ${brief.recommendation}`);
  }

  // 2. Check evidence references
  if (brief.executiveSummary !== "INSUFFICIENT_EVIDENCE") {
    if (!brief.evidenceRefs || brief.evidenceRefs.length === 0) {
      violations.push("Brief must cite at least one evidence reference");
    }
    for (const ref of brief.evidenceRefs || []) {
      if (!validRefs.has(ref)) {
        violations.push(`Brief cites unknown evidence reference: ${ref}`);
      }
    }
  }

  // 3. Claims validation
  const claimIds = new Set<string>();
  const claimTexts = new Set<string>();
  for (const claim of brief.claims || []) {
    if (claimIds.has(claim.claimId)) {
      violations.push(`Duplicate claimId: ${claim.claimId}`);
    }
    claimIds.add(claim.claimId);

    const normText = claim.claimText.trim().toLowerCase();
    if (claimTexts.has(normText)) {
      violations.push(`Duplicate claim content: "${claim.claimText}"`);
    }
    claimTexts.add(normText);

    if (!claim.evidenceRefs || claim.evidenceRefs.length === 0) {
      violations.push(`Claim ${claim.claimId} must cite at least one evidence reference`);
    }
    for (const ref of claim.evidenceRefs || []) {
      if (!validRefs.has(ref)) {
        violations.push(`Claim ${claim.claimId} cites unknown evidence reference: ${ref}`);
      }
    }
  }

  // 4. Numbers check (no manufactured metrics/hallucinations)
  const allowedNumbers = new Set<number>();
  const addNumbers = (text: string) => {
    for (const match of text.matchAll(/\d+(?:\.\d+)?/g)) {
      allowedNumbers.add(Math.abs(parseFloat(match[0])));
    }
  };

  // Extract all numbers from the registry details
  for (const r of registry) {
    addNumbers(r.detail);
    addNumbers(r.label);
  }

  // Common allowed small numbers
  allowedNumbers.add(0);
  allowedNumbers.add(1);
  allowedNumbers.add(2);
  allowedNumbers.add(3);
  allowedNumbers.add(5);
  allowedNumbers.add(10);
  allowedNumbers.add(brief.claims.length);
  allowedNumbers.add(registry.length);

  const checkTextNumbers = (text: string, contextLabel: string) => {
    for (const match of text.matchAll(/\d+(?:\.\d+)?/g)) {
      const n = Math.abs(parseFloat(match[0]));
      // Exclude years 2000-2100
      if (n >= 2000 && n <= 2100) continue;
      if (!allowedNumbers.has(n) && !allowedNumbers.has(Math.round(n))) {
        violations.push(`${contextLabel}: contains fabricated statistic/number "${match[0]}"`);
      }
    }
  };

  checkTextNumbers(brief.executiveSummary, "Executive Summary");
  checkTextNumbers(brief.strategicInterpretation, "Strategic Interpretation");
  for (const claim of brief.claims || []) {
    checkTextNumbers(claim.claimText, `Claim ${claim.claimId}`);
  }

  return violations;
}

// Derived confidence score builder
export function calculateDerivedConfidence(
  brief: LLMBriefResponse,
  registry: EvidenceRegistryEntry[],
  judgeResult: JudgeResult | null
): { finalConfidence: number; adjustmentReasons: string[] } {
  let score = brief.modelProposedConfidence || 75;
  const reasons: string[] = [];

  // Deduct based on stale evidence
  const staleCount = registry.filter((r) => r.freshnessStatus === "stale").length;
  if (staleCount > 0) {
    score -= staleCount * 3;
    reasons.push(`Stale evidence penalty: -${staleCount * 3}%`);
  }

  // Deduct based on historical count (thin context)
  const historicalCount = registry.filter((r) => r.freshnessStatus === "historical").length;
  if (registry.length < 5) {
    score -= 15;
    reasons.push("Low evidence coverage penalty: -15%");
  }

  // Deduct based on proportion of inferred facts
  const claims = brief.claims || [];
  const inferredCount = claims.filter((c) => c.factuality === "inferred").length;
  if (claims.length > 0 && inferredCount / claims.length > 0.6) {
    score -= 10;
    reasons.push("High proportion of inferred claims penalty: -10%");
  }

  // Deduct based on judge partially supported claims
  if (judgeResult) {
    const partialCount = judgeResult.claims.filter((c) => c.verdict === "partially_supported").length;
    if (partialCount > 0) {
      score -= partialCount * 5;
      reasons.push(`Partially supported claims penalty: -${partialCount * 5}%`);
    }
  }

  const finalConfidence = Math.max(10, Math.min(100, score));
  return { finalConfidence, adjustmentReasons: reasons };
}

// Strategic Brief Generator LLM Flow
export async function runStrategicInterpreter(
  eventId: string,
  registry: EvidenceRegistryEntry[],
  accountId: string,
  previousViolations?: string[]
): Promise<LLMBriefResponse> {
  const payload = {
    eventId,
    evidenceRegistry: registry.map((r) => ({
      ref: r.ref,
      origin: r.origin,
      timestamp: r.timestamp,
      factType: r.factType,
      detail: r.detail,
    })),
  };

  let lastError = previousViolations && previousViolations.length > 0
    ? `Grounding Judge rejected previous brief: ${previousViolations.join("; ")}`
    : "";

  for (let attempt = 1; attempt <= 2; attempt++) {
    let userContent =
      attempt === 1 && !lastError
        ? `Generate strategic brief for event ${eventId}. Evidence context:\n${JSON.stringify(payload, null, 2)}`
        : `Generate strategic brief for event ${eventId}. Evidence context:\n${JSON.stringify(payload, null, 2)}\n\n[SELF-CORRECTION FEEDBACK] The previous brief attempt failed validation: ${lastError}.
FIX INSTRUCTIONS:
1. Do NOT invent unobserved competitor motives or intent (e.g. "attempt to revitalize engagement").
2. Ensure every claim CL-x is strictly grounded in observable facts from the cited evidence.
3. Express inferences cautiously with qualifying words.
Return clean structured JSON only.`;

    try {
      const result = await callCommercialReasoner({
        accountId,
        endpoint: "strategic-brief-generator",
        systemPrompt: GENERATOR_SYSTEM_PROMPT,
        userPrompt: userContent,
      });

      const parsed = result.parsed as LLMBriefResponse;
      if (!parsed.eventId || !parsed.executiveSummary || !parsed.strategicInterpretation) {
        throw new Error("Missing required strategic brief fields in JSON output");
      }
      return parsed;
    } catch (err: any) {
      lastError = err?.message || String(err);
    }
  }

  throw new Error(`Strategic brief generator failed: ${lastError}`);
}

// Grounding LLM Judge call
export async function runBriefJudge(
  brief: LLMBriefResponse,
  registry: EvidenceRegistryEntry[],
  accountId: string
): Promise<JudgeResult> {
  const payload = {
    evidenceRegistry: registry.map((r) => ({
      ref: r.ref,
      detail: r.detail,
    })),
    claims: brief.claims.map((c) => ({
      claimId: c.claimId,
      claimText: c.claimText,
      evidenceRefs: c.evidenceRefs,
      criticality: c.criticality,
    })),
  };

  try {
    const result = await callCommercialReasoner({
      accountId,
      endpoint: "strategic-brief-judge",
      systemPrompt: JUDGE_SYSTEM_PROMPT,
      userPrompt: `Validate the grounding of these claims:\n${JSON.stringify(payload, null, 2)}`,
    });

    const parsed = result.parsed as JudgeResult;
    if (!parsed.verdict || !Array.isArray(parsed.claims)) {
      throw new Error("Invalid judge output schema");
    }
    return parsed;
  } catch (err: any) {
    console.error("[BriefJudge] failed:", err);
    // Safe fallback to failing the run
    return {
      verdict: "REJECT",
      claims: brief.claims.map((c) => ({
        claimId: c.claimId,
        verdict: "unsupported",
        violations: ["Grounding judge call failed: " + (err?.message || String(err))],
        judgeReason: "Execution failure",
      })),
    };
  }
}
