export const CONTROL_VERSION = "3.0.0";

export const STRUCTURAL_THRESHOLDS = {
  INTEGRITY_FAIL_BLOCK: true,
  INTEGRITY_PARTIAL_RESTRICT: true,
  SCALE_REQUIRES_REAL_DATA: true,
  CONVERSION_PATH_REQUIRED: true,
  CEL_FAILURE_BLOCKS: true,
} as const;

export const BUDGET_DOWNGRADE_RULES = {
  SCALE_WITHOUT_CAC_DATA: "test",
  SCALE_WITH_WEAK_FUNNEL: "test",
  TEST_WITH_PARTIAL_INTEGRITY: "hold",
} as const;

export const FUNNEL_STRENGTH_MINIMUM_FOR_SCALE = 0.5;
export const SIGNAL_TRUST_MINIMUM_FOR_LAUNCH = 0.3;
export const INTEGRITY_RESTRICT_THRESHOLD = 0.6;

export const SIGNAL_GROUNDING_FAILURE_THRESHOLD = 5;
export const CHANNEL_CONFIDENCE_MINIMUM = 0.5;
export const OFFER_PAIN_ALIGNMENT_PENALTY = 0.25;
export const OFFER_ZERO_OBJECTION_PENALTY = 0.20;
export const PERSUASION_UNMAPPED_PROOF_PENALTY = 0.15;
export const PERSUASION_POSITIONING_DRIFT_PENALTY = 0.20;
