import { describe, it, expect } from "vitest";
import "dotenv/config";
import { buildReasonedStructuredObjections, buildPersuasionResponse } from "../persuasion-engine/engine";
import type {
  PersuasionAudienceInput,
  PersuasionMIInput,
  PersuasionPositioningInput,
  PersuasionDifferentiationInput,
  PersuasionOfferInput,
  PersuasionAwarenessInput,
} from "../persuasion-engine/types";

const MOCK_AUDIENCE: PersuasionAudienceInput = {
  audiencePains: [
    { pain: "Disconnected Data Insights Hindering Targeting", description: "Disconnected insights lead to inaccurate targeting", canonical: "Disconnected Data Insights Hindering Targeting" },
    { pain: "High setup overhead and workflow friction", description: "Complex onboarding disrupts operational velocity", canonical: "High setup overhead and workflow friction" }
  ],
  emotionalDrivers: ["confidence", "efficiency"],
  sophisticationTier: 3,
  painRegistry: [
    {
      painId: "pain_obj_1",
      canonical: "Skepticism about real-time multi-source data sync reliability",
      classification: "OBJECTION",
      severity: "high"
    },
    {
      painId: "pain_obj_2",
      canonical: "Fear of high ongoing integration maintenance overhead",
      classification: "OBJECTION",
      severity: "high"
    }
  ] as any,
  laneContext: {
    laneId: "lane_test_1",
    laneTitle: "Data Quality and Decision Enablement",
    description: "Focuses on automated real-time validation and structuring of market data",
    corePainIds: ["pain_obj_1", "pain_obj_2"],
    targetRole: "Digital Operations & Automation Strategy Leads"
  } as any
};

const MOCK_MI: PersuasionMIInput = {
  marketDiagnosis: "ESTABLISHED_COMPETITION",
  overallConfidence: 0.9,
  opportunitySignals: [],
  threatSignals: [],
  narrativeObjectionCount: 0,
  narrativeObjections: []
};

const MOCK_POSITIONING: PersuasionPositioningInput = {
  narrativeDirection: "Evidence-grounded operational intelligence replacing fragmented manual scraping",
  positioningStatement: "Avyron AI is the autonomous market intelligence platform for digital operators",
  enemyDefinition: "Fragmented, manual, unvalidated signal scraping",
  confidence: 0.9
};

const MOCK_DIFFERENTIATION: PersuasionDifferentiationInput = {
  pillars: ["Integrated real-time multi-source market signal streaming with automated semantic filtering"],
  claimStructures: ["Automated operational intelligence generation from validated live market data streams"],
  confidence: 0.9
};

const MOCK_OFFER: PersuasionOfferInput = {
  coreOutcome: "Continuous verified market intelligence pipeline",
  mechanismDescription: "Autonomous multi-source validation engine with deterministic semantic governance",
  riskNotes: ["Requires initial account configuration"],
  confidence: 0.9
};

const MOCK_AWARENESS: PersuasionAwarenessInput = {
  targetReadinessStage: "solution_aware",
  confidence: 0.9
};

const MOCK_PRODUCT_DNA = {
  targetRoles: ["Digital Operations Lead", "Automation Strategy Lead"],
  targetDecisionMaker: "Digital Operations Lead",
  coreOffer: "Autonomous Market Intelligence System",
  uniqueMechanism: "Integrated real-time multi-source market signal streaming with automated semantic filtering",
  productTruthFacts: [
    {
      productTruthFactId: "fact_1",
      factType: "CAPABILITY",
      statement: "Ingests and structures live multi-source signals with sub-second latency and zero manual tagging"
    },
    {
      productTruthFactId: "fact_2",
      factType: "GOVERNANCE",
      statement: "Enforces strict Causal Enforcement Layer (CEL) depth gating and semantic boundary verification"
    }
  ]
};

describe("Persuasion Objection Cleanup & Reasoner Hardening", () => {
  it("Test 1: production objection response is generated by Persuasion reasoning, not buildPersuasionResponse", async () => {
    const results = await buildReasonedStructuredObjections(
      MOCK_AUDIENCE,
      MOCK_MI,
      MOCK_POSITIONING,
      MOCK_DIFFERENTIATION,
      MOCK_OFFER,
      MOCK_AWARENESS,
      null,
      MOCK_PRODUCT_DNA as any,
      null,
      "test-account-1"
    );

    expect(results.length).toBeGreaterThan(0);
    for (const obj of results) {
      expect(obj.persuasionResponse).toBeDefined();
      expect(obj.persuasionResponse.length).toBeGreaterThan(25);

      // Verify NO deterministic template strings
      expect(obj.persuasionResponse).not.toContain("Address credibility concern with third-party validation");
      expect(obj.persuasionResponse).not.toContain("Simplify with step-by-step mechanism explanation");
      expect(obj.persuasionResponse).not.toContain("Demonstrate proven process and real outcomes");
      expect(obj.persuasionResponse).not.toContain("Reframe value proposition with ROI evidence");
      expect(obj.persuasionResponse).not.toContain("Provide specific proof addressing");
    }
  }, 45000);

  it("Test 2: two different objections receive independently reasoned responses, not category-prefix templates", async () => {
    const results = await buildReasonedStructuredObjections(
      MOCK_AUDIENCE,
      MOCK_MI,
      MOCK_POSITIONING,
      MOCK_DIFFERENTIATION,
      MOCK_OFFER,
      MOCK_AWARENESS,
      null,
      MOCK_PRODUCT_DNA as any,
      null,
      "test-account-1"
    );

    expect(results.length).toBe(2);
    const resp1 = results[0].persuasionResponse;
    const resp2 = results[1].persuasionResponse;

    // Both responses must be distinct and non-identical
    expect(resp1).not.toEqual(resp2);

    // Neither should start with hardcoded prefix patterns
    expect(resp1.toLowerCase().startsWith("address credibility concern")).toBe(false);
    expect(resp2.toLowerCase().startsWith("demonstrate proven process")).toBe(false);
    expect(resp1.toLowerCase().startsWith("simplify with step-by-step")).toBe(false);
  }, 45000);

  it("Test 3: PROOF_TO_BUILD cannot produce 'proven outcomes' as existing proof", async () => {
    const results = await buildReasonedStructuredObjections(
      MOCK_AUDIENCE,
      MOCK_MI,
      MOCK_POSITIONING,
      MOCK_DIFFERENTIATION,
      MOCK_OFFER,
      MOCK_AWARENESS,
      null,
      MOCK_PRODUCT_DNA as any,
      null,
      "test-account-1"
    );

    for (const obj of results) {
      if (obj.proofStatus === "PROOF_TO_BUILD") {
        const lower = obj.persuasionResponse.toLowerCase();
        expect(lower).not.toContain("proven outcomes");
        expect(lower).not.toContain("our customer results");
        expect(lower).not.toContain("existing case studies");
        expect(lower).not.toContain("demonstrated success");
      }
    }
  }, 45000);

  it("Test 4: missing/invalid response -> Judge -> bounded retry -> fail closed", async () => {
    const invalidAudience: PersuasionAudienceInput = {
      audiencePains: [],
      emotionalDrivers: [],
      sophisticationTier: 1,
      painRegistry: []
    };

    // When there are no candidate objections at all, returns empty array safely
    const emptyResults = await buildReasonedStructuredObjections(
      invalidAudience,
      MOCK_MI,
      MOCK_POSITIONING,
      MOCK_DIFFERENTIATION,
      MOCK_OFFER,
      MOCK_AWARENESS,
      null,
      null,
      null,
      "test-account-1"
    );

    expect(emptyResults).toEqual([]);
  });

  it("Test 5: Plan Synthesis receives canonical Persuasion response fields unchanged", async () => {
    const results = await buildReasonedStructuredObjections(
      MOCK_AUDIENCE,
      MOCK_MI,
      MOCK_POSITIONING,
      MOCK_DIFFERENTIATION,
      MOCK_OFFER,
      MOCK_AWARENESS,
      null,
      MOCK_PRODUCT_DNA as any,
      null,
      "test-account-1"
    );

    expect(results.length).toBeGreaterThan(0);
    const obj = results[0];
    expect(obj.objectionId).toBeDefined();
    expect(obj.objectionStatement).toBeDefined();
    expect(obj.persuasionResponse).toBeDefined();
    expect(obj.requiredProofType).toBeDefined();
    expect(obj.proofStatus).toBe("PROOF_TO_BUILD");
  }, 45000);
});
